export const RUN_TYPES = {
  easy_run: { purpose: 'Build aerobic endurance without tiring yourself out.', effort: 'Easy · RPE 3–4/10. You can speak in full sentences.', rule: 'Let effort set the pace. Slow down or walk on hills or in heat.', block: false, warmup: 5, cooldown: 5, work: 20, recovery: 0, rounds: 1 },
  recovery_run: { purpose: 'Gentle movement between harder training days.', effort: 'Very easy · RPE 2–3/10. Conversation feels effortless.', rule: 'Keep it shorter and easier than your usual easy run. Rest instead if fatigued or in pain.', block: false, warmup: 5, cooldown: 5, work: 15, recovery: 0, rounds: 1 },
  zone2_run: { purpose: 'Steady aerobic work at a comfortable intensity.', effort: 'Conversational · RPE 3–4/10. Slow down if you cannot talk comfortably.', rule: 'This app uses Zone 2 = 60–70% of maximum HR in a five-zone %HRmax system. Watch zones may use a different method. A tested aerobic threshold is more individual.', block: false, warmup: 10, cooldown: 5, work: 25, recovery: 0, rounds: 1 },
  maf_run: { purpose: 'Aerobic training using the MAF 180-formula heart-rate ceiling.', effort: 'Comfortable aerobic effort. Do not chase a fixed pace.', rule: 'Main run at or below the MAF ceiling; slow down or walk when HR rises. MAF is a training heuristic, not your maximum heart rate or a medical test.', block: false, warmup: 15, cooldown: 10, work: 20, recovery: 0, rounds: 1 },
  long_run: { purpose: 'Build time-on-feet and endurance.', effort: 'Easy · RPE 3–4/10. Maintain a conversational effort.', rule: 'Duration must fit your current training. 60 minutes is only an editable example, not a beginner prescription. Increase gradually and plan fluids for heat.', block: false, warmup: 5, cooldown: 5, work: 50, recovery: 0, rounds: 1 },
  tempo_run: { purpose: 'Sustain a comfortably hard effort to develop endurance at speed.', effort: 'Controlled hard · RPE 6–7/10. Short phrases, not full conversation.', rule: 'Use your current threshold effort—not an aspirational race pace. Keep it controlled, not an all-out race.', block: false, warmup: 10, cooldown: 10, work: 15, recovery: 0, rounds: 1 },
  interval_run: { purpose: 'Repeated faster efforts separated by easy recovery.', effort: 'Work: RPE 7–8/10. Recovery: easy jog or walk.', rule: 'Keep each repetition repeatable with good form. Recover between efforts; stop if quality drops. These are adjustable examples, not maximal sprints.', block: true, warmup: 10, cooldown: 10, work: 2, recovery: 2, rounds: 5 },
  fartlek_run: { purpose: 'Speed play: mix quicker and easier running without rigid pace targets.', effort: 'Quicker: RPE 6–7/10. Easy: conversational jogging.', rule: 'Keep moving between efforts. Use timed blocks below or landmarks outdoors. Fartlek is flexible; this is one structured example.', block: true, warmup: 10, cooldown: 10, work: 1, recovery: 2, rounds: 6 },
  hill_run: { purpose: 'Short uphill efforts for strength and running technique.', effort: 'Controlled hard uphill · RPE 7/10. Easy walk/jog recovery.', rule: 'Choose a manageable slope and keep posture controlled. Descend easily; extend recovery until ready rather than rushing downhill.', block: true, warmup: 10, cooldown: 10, work: .5, recovery: 2, rounds: 6 },
} as const
export type RunKind = keyof typeof RUN_TYPES
export type RunSettings = { warmup: number; cooldown: number; work: number; recovery: number; rounds: number; maxHr: number; mafAdjustment: number; distanceKm: string; averageHr: string }
export function initialRunSettings(kind: RunKind, age: number): RunSettings {
  const type = RUN_TYPES[kind]
  return { warmup: type.warmup, cooldown: type.cooldown, work: type.work, recovery: type.recovery, rounds: type.rounds, maxHr: Math.round(220-age), mafAdjustment: -5, distanceKm: '', averageHr: '' }
}
export function plannedRunMinutes(kind: RunKind, s: RunSettings) { return s.warmup + s.cooldown + s.work * s.rounds + (RUN_TYPES[kind].block ? s.recovery * Math.max(0, s.rounds - 1) : 0) }
export function validRunSettings(s: RunSettings) { return [s.warmup,s.cooldown].every(v=>Number.isFinite(v)&&v>=0&&v<=120) && Number.isFinite(s.work)&&s.work>0&&s.work<=600 && Number.isInteger(s.rounds)&&s.rounds>=1&&s.rounds<=50 && Number.isFinite(s.recovery)&&s.recovery>=0&&s.recovery<=120 && Number.isFinite(s.maxHr)&&s.maxHr>=80&&s.maxHr<=240 && [-10,-5,0,5].includes(s.mafAdjustment) && (s.distanceKm==='' || (Number.isFinite(+s.distanceKm)&&+s.distanceKm>0&&+s.distanceKm<=250)) && (s.averageHr==='' || (Number.isFinite(+s.averageHr)&&+s.averageHr>=30&&+s.averageHr<=240)) }
