/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'secondary': '#13786a',
        'secondary-container': '#def4ed',
        'inverse-primary': '#2453ee',
        'on-error': '#ffffff',
        'surface-tint': '#2453ee',
        'surface-variant': '#e8edf5',
        'tertiary': '#a94f24',
        'on-tertiary-container': '#783719',
        'on-secondary-fixed': '#00201c',
        'on-secondary-fixed-variant': '#005047',
        'surface-bright': '#ffffff',
        'surface': '#f4f6fa',
        'secondary-fixed': '#62fae3',
        'inverse-surface': '#e5e1e4',
        'on-surface-variant': '#627089',
        'on-surface': '#17253a',
        'primary-container': '#e8eeff',
        'outline-variant': '#dfe5ef',
        'on-tertiary': '#4f2500',
        'on-primary-fixed': '#140067',
        'primary': '#2453ee',
        'tertiary-container': '#fff0e5',
        'on-secondary': '#ffffff',
        'secondary-fixed-dim': '#3cddc7',
        'surface-container-low': '#f4f6fa',
        'on-secondary-container': '#145e54',
        'primary-fixed': '#e3dfff',
        'surface-dim': '#eef2f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e8edf5',
        'error-container': '#fff1f0',
        'on-tertiary-fixed-variant': '#713700',
        'surface-container': '#ffffff',
        'primary-fixed-dim': '#c5c0ff',
        'inverse-on-surface': '#303032',
        'tertiary-fixed': '#ffdcc5',
        'on-error-container': '#b53b35',
        'tertiary-fixed-dim': '#ffb783',
        'on-background': '#17253a',
        'on-primary-container': '#244caa',
        'error': '#b53b35',
        'on-primary-fixed-variant': '#3f35a3',
        'on-primary': '#ffffff',
        'surface-container-highest': '#e2e9f4',
        'background': '#f4f6fa',
        'outline': '#73819a',
        'on-tertiary-fixed': '#301400',
        // Design-spec card tiers (DESIGN.md Elevation)
        'tile': '#ffffff',
        'tile-border': '#dfe5ef',
        // Vibrant fitness palette (motion redesign)
        'lime': '#2453ee',
        'lime-dim': '#1d45c9',
        'on-lime': '#ffffff',
        'lilac': '#e8eeff',
        'lilac-deep': '#dce5ff',
        'on-lilac': '#241a3d',
        'pink': '#fff0e5',
        'pink-deep': '#f8ddce',
        'on-pink': '#3d1a30',
        'violet': '#2453ee',
        'ink': '#f4f6fa',
        'ink-card': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        xl: '40px',
        lg: '24px',
        base: '4px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        gutter: '16px',
      },
      fontFamily: {
        'metric-md': ['Hanken Grotesk', 'sans-serif'],
        'display-hero': ['Hanken Grotesk', 'sans-serif'],
        'label-caps': ['Hanken Grotesk', 'sans-serif'],
        'headline-lg-mobile': ['Hanken Grotesk', 'sans-serif'],
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'data-mono': ['Hanken Grotesk', 'sans-serif'],
        'headline-lg': ['Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        'metric-md': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'display-hero': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'data-mono': ['14px', { lineHeight: '1.4', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
