/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        secondary: '#44e2cd',
        'secondary-container': '#03c6b2',
        'inverse-primary': '#584fbc',
        'on-error': '#690005',
        'surface-tint': '#c5c0ff',
        'surface-variant': '#353437',
        tertiary: '#ffb783',
        'on-tertiary-container': '#ffc69f',
        'on-secondary-fixed': '#00201c',
        'on-secondary-fixed-variant': '#005047',
        'surface-bright': '#39393b',
        surface: '#131315',
        'secondary-fixed': '#62fae3',
        'inverse-surface': '#e5e1e4',
        'on-surface-variant': '#c8c4d5',
        'on-surface': '#e5e1e4',
        'primary-container': '#534ab7',
        'outline-variant': '#474553',
        'on-tertiary': '#4f2500',
        'on-primary-fixed': '#140067',
        primary: '#c5c0ff',
        'tertiary-container': '#8d4700',
        'on-secondary': '#003731',
        'secondary-fixed-dim': '#3cddc7',
        'surface-container-low': '#1b1b1d',
        'on-secondary-container': '#004d44',
        'primary-fixed': '#e3dfff',
        'surface-dim': '#131315',
        'surface-container-lowest': '#0e0e10',
        'surface-container-high': '#2a2a2c',
        'error-container': '#93000a',
        'on-tertiary-fixed-variant': '#713700',
        'surface-container': '#201f21',
        'primary-fixed-dim': '#c5c0ff',
        'inverse-on-surface': '#303032',
        'tertiary-fixed': '#ffdcc5',
        'on-error-container': '#ffdad6',
        'tertiary-fixed-dim': '#ffb783',
        'on-background': '#e5e1e4',
        'on-primary-container': '#d1ccff',
        error: '#ffb4ab',
        'on-primary-fixed-variant': '#3f35a3',
        'on-primary': '#28188c',
        'surface-container-highest': '#353437',
        background: '#131315',
        outline: '#928f9e',
        'on-tertiary-fixed': '#301400',
        // Design-spec card tiers (DESIGN.md Elevation)
        'tile': '#1E1E21',
        'tile-border': '#2E2E32',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        xl: '40px',
        lg: '24px',
        base: '4px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        gutter: '16px',
      },
      fontFamily: {
        'metric-md': ['Hanken Grotesk', 'sans-serif'],
        'display-hero': ['Hanken Grotesk', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Hanken Grotesk', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'data-mono': ['JetBrains Mono', 'monospace'],
        'headline-lg': ['Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        'metric-md': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'display-hero': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'data-mono': ['14px', { lineHeight: '1.4', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
