/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'secondary': 'var(--palette-success)',
        'secondary-container': 'var(--palette-success-bg)',
        'inverse-primary': 'var(--palette-accent)',
        'on-error': 'var(--palette-on-accent)',
        'surface-tint': 'var(--palette-accent)',
        'surface-variant': 'var(--palette-soft)',
        'tertiary': '#a94f24',
        'on-tertiary-container': '#783719',
        'on-secondary-fixed': '#00201c',
        'on-secondary-fixed-variant': '#005047',
        'surface-bright': 'var(--palette-surface)',
        'surface': 'var(--palette-bg)',
        'secondary-fixed': '#62fae3',
        'inverse-surface': '#e5e1e4',
        'on-surface-variant': 'var(--palette-muted)',
        'on-surface': 'var(--palette-ink)',
        'primary-container': 'var(--palette-tint)',
        'outline-variant': 'var(--palette-line)',
        'on-tertiary': '#4f2500',
        'on-primary-fixed': '#140067',
        'primary': 'var(--palette-accent)',
        'tertiary-container': '#fff0e5',
        'on-secondary': 'var(--palette-on-accent)',
        'secondary-fixed-dim': '#3cddc7',
        'surface-container-low': 'var(--palette-bg)',
        'on-secondary-container': 'var(--palette-success)',
        'primary-fixed': '#e3dfff',
        'surface-dim': 'var(--palette-bg)',
        'surface-container-lowest': 'var(--palette-surface)',
        'surface-container-high': 'var(--palette-soft)',
        'error-container': 'var(--palette-error-bg)',
        'on-tertiary-fixed-variant': '#713700',
        'surface-container': 'var(--palette-surface)',
        'primary-fixed-dim': '#c5c0ff',
        'inverse-on-surface': '#303032',
        'tertiary-fixed': '#ffdcc5',
        'on-error-container': 'var(--palette-error)',
        'tertiary-fixed-dim': '#ffb783',
        'on-background': 'var(--palette-ink)',
        'on-primary-container': 'var(--palette-accent)',
        'error': 'var(--palette-error)',
        'on-primary-fixed-variant': '#3f35a3',
        'on-primary': 'var(--palette-on-accent)',
        'surface-container-highest': 'var(--palette-soft)',
        'background': 'var(--palette-bg)',
        'outline': 'var(--palette-muted)',
        'on-tertiary-fixed': '#301400',
        // Design-spec card tiers (DESIGN.md Elevation)
        'tile': 'var(--palette-surface)',
        'tile-border': 'var(--palette-line)',
        // Vibrant fitness palette (motion redesign)
        'lime': 'var(--palette-accent)',
        'lime-dim': 'var(--palette-hover)',
        'on-lime': 'var(--palette-on-accent)',
        'lilac': 'var(--palette-tint)',
        'lilac-deep': 'var(--palette-tint)',
        'on-lilac': '#241a3d',
        'pink': '#fff0e5',
        'pink-deep': '#f8ddce',
        'on-pink': '#3d1a30',
        'violet': 'var(--palette-accent)',
        'ink': 'var(--palette-bg)',
        'ink-card': 'var(--palette-surface)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        xl: '40px',
        lg: '24px',
        base: '4px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        gutter: '16px',
      },
      fontFamily: {
        'metric-md': ['Hanken Grotesk', 'sans-serif'],
        'display-hero': ['Hanken Grotesk', 'sans-serif'],
        'label-caps': ['Hanken Grotesk', 'sans-serif'],
        'headline-lg-mobile': ['Hanken Grotesk', 'sans-serif'],
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'data-mono': ['Hanken Grotesk', 'sans-serif'],
        'headline-lg': ['Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        'metric-md': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'display-hero': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'data-mono': ['14px', { lineHeight: '1.4', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
