import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useApp } from '../store/AppContext'
import { TopBar } from '../components/TopBar'
import { Icon } from '../components/Icon'
import { addDays, daysBetween, shortDate, todayISO, weekday } from '../lib/date'
import { RACE_OPTIONS, formatFinishTime, formatPace, generatePlan, parseRunTime, planCapability, planPhase, planWeeks, raceLabel, suggestPlanStart } from '../lib/plan'
import type { RaceType, UserProfile } from '../types'
import './running.css'

const DAYS=['Mon','Tue','Wed','Thu','Fri','Sat','Sun']
export function Train() {
  const { profile, state, weightKg, updateProfile, toggleSession }=useApp()
  const nav=useNavigate()
  const [view,setView]=useState<'setup'|'schedule'|'paces'>(profile.planStartDate?'schedule':'setup')
  const [draft,setDraft]=useState<UserProfile>({...profile,trainingDaysPerWeek:Math.max(3,Math.min(6,profile.trainingDaysPerWeek)),runPreferredDays:profile.runPreferredDays.length===Math.max(3,Math.min(6,profile.trainingDaysPerWeek))?profile.runPreferredDays:[1,3,5,0,4,6].slice(0,Math.max(3,Math.min(6,profile.trainingDaysPerWeek))),planStartDate:profile.planStartDate??suggestPlanStart()})
  const [goalText,setGoalText]=useState(profile.runGoalTimeMin?formatFinishTime(profile.runGoalTimeMin):'30:00')
  const [timed,setTimed]=useState(Boolean(profile.runGoalTimeMin))
  const [resultText,setResultText]=useState(formatFinishTime((profile.runBenchmarkDistanceKm===10?profile.bestTenKmPaceSecPerKm*10:profile.bestFiveKmPaceSecPerKm*5)/60))
  const [error,setError]=useState('')
  const [saved,setSaved]=useState(false)
  const [weekIndex,setWeekIndex]=useState(Math.max(0,profile.planStartDate?Math.min(planWeeks(profile)-1,Math.floor(daysBetween(profile.planStartDate,todayISO())/7)):0))
  const goal=parseRunTime(goalText),result=parseRunTime(resultText)
  const previewProfile=useMemo(()=>({...draft,runGoalTimeMin:timed?goal:null,
    ...(draft.runBenchmarkKnown&&result?draft.runBenchmarkDistanceKm===5?{bestFiveKmPaceSecPerKm:result*60/5}:{bestTenKmPaceSecPerKm:result*60/10}:{})}),[draft,timed,goal,result])
  const preview=useMemo(()=>generatePlan(previewProfile,weightKg),[previewProfile,weightKg])
  const cap=planCapability(previewProfile),activeCap=planCapability(profile)
  const total=planWeeks(profile),activeStart=profile.planStartDate??suggestPlanStart()
  const weekStart=addDays(activeStart,weekIndex*7),weekEnd=addDays(weekStart,7)
  const sessions=state.sessions.filter(s=>s.plan==='running'&&s.date>=weekStart&&s.date<weekEnd).sort((a,b)=>a.date.localeCompare(b.date))
  const requiredPace=goal?goal*60/cap.raceKm:null
  function changeRace(type:RaceType) {
    const race=RACE_OPTIONS.find(r=>r.id===type)!
    setDraft(p=>({...p,raceType:type,runPlanWeeks:race.weeks}))
    setGoalText(formatFinishTime(race.presets[type==='5k'||type==='10k'?2:1]));setSaved(false)
  }
  function save() {
    if(timed&&!goal){setError('Enter a finish time as mm:ss or h:mm:ss, for example 30:00 or 1:00:00.');return}
    if(draft.runBenchmarkKnown&&(!result||result*60/draft.runBenchmarkDistanceKm<120||result*60/draft.runBenchmarkDistanceKm>1800)){setError('Enter a recent 5K or 10K result with a pace between 2:00 and 30:00 per km.');return}
    if(!Number.isFinite(draft.bestRunDistanceKm)||draft.bestRunDistanceKm<1||draft.bestRunDistanceKm>100){setError('Enter a longest comfortable run between 1 and 100 km.');return}
    if(draft.runPreferredDays.length!==draft.trainingDaysPerWeek){setError('Choose exactly your available number of training days.');return}
    if(!draft.planStartDate||draft.raceDate&&(daysBetween(draft.planStartDate,draft.raceDate)<6||daysBetween(draft.planStartDate,draft.raceDate)>365)){setError('Race date must be at least a week after the start and within one year.');return}
    updateProfile({...previewProfile,sports:profile.sports.includes('running')?profile.sports:[...profile.sports,'running']},true)
    setError('');setSaved(true);setWeekIndex(0);setView('schedule')
  }
  const status=cap.assessment.difficulty
  return <div className="run-page"><TopBar/><header className="page-heading"><h1>Your distance. Your finish.</h1><p>A 5K breakthrough or a marathon finish. Build from where you are.</p></header>
    <nav className="page-switch" aria-label="Running sections">{([{id:'setup',label:'Build a plan'},{id:'schedule',label:'Schedule'},{id:'paces',label:'Pace guide'}] as const).map(t=><button key={t.id} aria-pressed={view===t.id} onClick={()=>setView(t.id)}>{t.label}</button>)}</nav>
    {saved&&<p className="run-feedback" role="status">Plan saved on this device. Completed sessions and manual logs are kept.</p>}
    {view==='setup'&&<div className="run-setup">
      <section><h2>Choose your distance</h2><div className="run-distances" role="group" aria-label="Race distance">{RACE_OPTIONS.map(r=><button key={r.id} aria-pressed={draft.raceType===r.id} onClick={()=>changeRace(r.id)}><strong>{r.label}</strong><small>{r.km} km</small></button>)}</div></section>
      <section><h2>What are you chasing?</h2><div className="run-goal-mode"><button aria-pressed={!timed} onClick={()=>setTimed(false)}>Finish comfortably</button><button aria-pressed={timed} onClick={()=>setTimed(true)}>A finish time</button></div>
      {timed&&<><div className="run-time-presets">{RACE_OPTIONS.find(r=>r.id===draft.raceType)!.presets.map(min=><button key={min} aria-pressed={goal===min} onClick={()=>setGoalText(formatFinishTime(min))}>Sub {formatFinishTime(min)}</button>)}</div><label className="run-field">Custom finish time<input value={goalText} onChange={e=>setGoalText(e.target.value)} inputMode="text" placeholder="mm:ss or h:mm:ss" aria-describedby="run-time-help"/></label><p id="run-time-help" className="run-help">Any target: 28:30 means sub-28:30; 1:00:00 means sub-60 minutes.</p></>}
      <div className="run-goal-preview"><Icon name="flag" size={24}/><div><strong>{timed&&goal?`${raceLabel(draft.raceType)} · Sub ${formatFinishTime(goal)}`:'A confident finish'}</strong><span>{timed&&requiredPace?`${formatPace(requiredPace)} average race pace required`:'No time pressure. Build consistency and endurance.'}</span></div></div></section>
      <section><h2>Start with your actual ability</h2><label className="run-checkbox"><input type="checkbox" checked={draft.runBenchmarkKnown} onChange={e=>setDraft(p=>({...p,runBenchmarkKnown:e.target.checked}))}/> I have a recent timed 5K or 10K result</label>
      {draft.runBenchmarkKnown&&<div className="run-fields"><label className="run-field">Result distance<select value={draft.runBenchmarkDistanceKm} onChange={e=>{const km=Number(e.target.value) as 5|10;setDraft(p=>({...p,runBenchmarkDistanceKm:km}));setResultText(formatFinishTime((km===5?draft.bestFiveKmPaceSecPerKm*5:draft.bestTenKmPaceSecPerKm*10)/60))}}><option value={5}>5 km</option><option value={10}>10 km</option></select></label><label className="run-field">Recent finish time<input value={resultText} onChange={e=>setResultText(e.target.value)} placeholder="e.g. 35:00"/></label></div>}
      <label className="run-field">Longest comfortable run · km<input type="number" min="1" max="100" step=".1" value={draft.bestRunDistanceKm} onChange={e=>setDraft(p=>({...p,bestRunDistanceKm:Number(e.target.value)}))}/></label>
      <div className={`run-assessment ${status==='unrealistic'?'is-caution':''}`}><h3>{status==='unknown'?'Build a baseline first':status==='unrealistic'?'A longer-term ambition':status==='stretch'?'A stretch from your recent result':status==='realistic'?'Within your current result estimate':'Build toward a comfortable finish'}</h3><p>{status==='unknown'?'Without a timed result, the plan uses conversational run/walk effort. Race-time readiness cannot be estimated yet.':`Your recent ${cap.assessment.benchmarkKm}K predicts roughly ${formatFinishTime(cap.assessment.baselineFinishMin)} for this distance. It is a heuristic, not a fitness test or guarantee.`}</p>{status==='unrealistic'&&<p>Training effort stays based on current ability. Repeat a benchmark after several weeks; do not force the goal pace on every run.</p>}{cap.assessment.capacityWarning&&<p>{cap.assessment.capacityWarning}</p>}</div></section>
      <section><h2>Fit training into your week</h2><div className="run-fields"><label className="run-field">Run days per week<select value={Math.min(6,draft.trainingDaysPerWeek)} onChange={e=>{const n=+e.target.value;setDraft(p=>({...p,trainingDaysPerWeek:n,runPreferredDays:[1,3,5,0,4,6].slice(0,n)}))}}>{[3,4,5,6].map(n=><option key={n} value={n}>{n} days</option>)}</select></label><label className="run-field">Training block<select value={draft.runPlanWeeks} onChange={e=>setDraft(p=>({...p,runPlanWeeks:+e.target.value}))}>{[4,6,8,10,12,14,16,18,20,24,26].map(n=><option key={n} value={n}>{n} weeks</option>)}</select></label></div>
      <div className="run-day-picker" role="group" aria-label="Preferred running days">{DAYS.map((d,i)=><button key={d} aria-pressed={draft.runPreferredDays.includes(i)} onClick={()=>setDraft(p=>({...p,runPreferredDays:p.runPreferredDays.includes(i)?p.runPreferredDays.filter(v=>v!==i):p.runPreferredDays.length<p.trainingDaysPerWeek?[...p.runPreferredDays,i]:p.runPreferredDays}))}>{d}</button>)}</div>
      <div className="run-fields"><label className="run-field">Start date<input type="date" value={draft.planStartDate??''} onChange={e=>setDraft(p=>({...p,planStartDate:e.target.value}))}/></label><label className="run-field">Event date · optional<input type="date" value={draft.raceDate??''} onChange={e=>setDraft(p=>({...p,raceDate:e.target.value||null}))}/></label></div><p className="run-help">An event date sets the actual plan length. The final week gets lighter and the event lands on its exact date. Keep at least one rest day.</p></section>
      <section className="run-plan-preview"><h2>What this plan includes</h2><p>{planWeeks(previewProfile)} weeks · {preview.filter(s=>s.zone==='Intervals'||s.zone==='Tempo').length} quality sessions · endurance + easy/recovery runs.</p><ul><li>{draft.raceType==='5k'?'Short controlled intervals and tempo blocks for 5K speed.':draft.raceType==='10k'?'Longer repetitions and sustained tempo blocks for 10K endurance.':draft.raceType==='half-marathon'?'Cruise intervals and gradually longer easy endurance for the half.':'Controlled endurance blocks and easy long runs for marathon preparation.'}</li><li>Warm-up, jog recovery and cool-down are included in workout time.</li><li>Effort guides come from your recent result, not an arbitrary target. Stop for pain or illness; adjust rather than catch up missed sessions.</li></ul></section>
      {error&&<p className="run-error" role="alert">{error}</p>}<button type="button" className="run-save" onClick={save}>{profile.planStartDate?'Update running plan':'Save my running plan'}<Icon name="arrow_forward" size={20}/></button>
    </div>}
    {view==='schedule'&&<section className="run-schedule">{!profile.planStartDate?<div className="run-empty"><h2>Your next start line.</h2><p>Choose your distance, time and available days to build a schedule.</p><button onClick={()=>setView('setup')}>Build my plan</button></div>:<>
      <div className="run-schedule-title"><h2>{raceLabel(profile.raceType)} · {activeCap.assessment.difficulty==='unrealistic'||activeCap.assessment.difficulty==='unknown'||activeCap.assessment.capacityWarning?'Foundation block':activeCap.selectedGoalLabel}</h2><p>{profile.runGoalTimeMin?`Ambition ${activeCap.selectedGoalLabel} · ${formatPace(profile.runGoalTimeMin*60/activeCap.raceKm)} required race pace · `:''}{profile.raceDate?`Event ${shortDate(profile.raceDate)}`:'No event date set'}</p></div>
      <div className="run-saved-assessment"><strong>{!profile.runBenchmarkKnown?'Add an actual recent result':activeCap.assessment.difficulty==='unrealistic'?'Your goal is ahead of your current benchmark':'Training from your current ability'}</strong><p>{profile.runBenchmarkKnown?`Saved benchmark: ${activeCap.assessment.benchmarkKm}K in ${formatFinishTime(activeCap.assessment.benchmarkKm*activeCap.assessment.benchmarkPace/60)}. Easy guide ${formatPace(activeCap.easyPace)}; current interval guide ${formatPace(activeCap.intervalPace)}.`:'Without a recent timed run, use conversational effort rather than numeric pace prescriptions.'}</p>{activeCap.assessment.difficulty==='unrealistic'&&<p>This is a foundation block, not a ready-to-race {activeCap.selectedGoalLabel} programme. Work at current ability, then repeat a benchmark and update the plan. Goal pace is not assigned to workouts yet.</p>}{activeCap.assessment.capacityWarning&&<p>{activeCap.assessment.capacityWarning}</p>}<button type="button" onClick={()=>setView('setup')}>Review result & goal <Icon name="arrow_forward" size={17}/></button></div>
      <div className="run-week-nav"><button aria-label="Previous training week" disabled={weekIndex===0} onClick={()=>setWeekIndex(i=>i-1)}><Icon name="chevron_left"/></button><div><strong>Week {weekIndex+1} / {total}</strong><span>{shortDate(weekStart)} – {shortDate(addDays(weekStart,6))}</span></div><button aria-label="Next training week" disabled={weekIndex>=total-1} onClick={()=>setWeekIndex(i=>i+1)}><Icon name="chevron_right"/></button></div>
      <p className="run-phase">{planPhase(weekIndex+1,total)} · {sessions.filter(s=>s.completed).length}/{sessions.length} sessions done</p>
      {Array.from({length:7},(_,i)=>addDays(weekStart,i)).map(date=>{const runs=sessions.filter(s=>s.date===date);return <div className="run-agenda-day" key={date}><div className="run-agenda-date"><strong>{weekday(date)}</strong><span>{shortDate(date)}</span></div><div>{runs.length?runs.map(s=><article className={`run-workout ${s.completed?'is-done':''}`} key={s.id}><div><h3>{s.title}</h3><p>{s.detail}</p><small>{s.durationMin} min · {s.distanceKm} km · {s.kcal} kcal estimate</small></div><button type="button" aria-pressed={s.completed} aria-label={`${s.completed?'Mark incomplete':'Complete'}: ${s.title} on ${date}`} onClick={()=>toggleSession(s.id)}><Icon name={s.completed?'check_circle':'radio_button_unchecked'} size={24}/></button></article>):<p className="run-rest">{date>addDays(activeStart,total*7-1)?'Outside this block': 'Rest / gentle mobility. No run scheduled.'}</p>}</div></div>})}
    </>}</section>}
    {view==='paces'&&<section className="run-paces"><h2>Train at the right effort</h2><p>These are approximate guides from your saved plan. Heat, hills, fatigue and recovery can change the pace.</p>{!profile.runBenchmarkKnown?<p className="run-assessment">No timed benchmark yet. Use conversational run/walk effort; add a recent result before relying on pace numbers.</p>:<div className="run-pace-list">{[{label:'Easy & long',pace:activeCap.easyPace,why:'Full sentences. Most of your running belongs here.'},{label:'Tempo',pace:activeCap.tempoPace,why:'Controlled, comfortably hard. Short phrases, not an all-out race.'},{label:'Intervals',pace:activeCap.intervalPace,why:'Short repetitions with easy jog recovery. Never sprint.'}].map(item=><div key={item.label}><div><h3>{item.label}</h3><p>{item.why}</p></div><strong>{formatPace(item.pace)}</strong></div>)}</div>}
      <details><summary>How the estimate works</summary><p>A recent result is scaled by time × (new distance / result distance)^1.06. This Riegel-style heuristic is especially uncertain for marathons, new runners and insufficient endurance. Targets more than 5% faster than that estimate are flagged; this is an app heuristic, not a clinical or coaching assessment.</p><p>Plans are original FitCore heuristics, not a copied coaching programme. They do not guarantee a sub-time.</p></details><a href="https://www.baa.org/races/boston-10k/info-for-athletes/b-a-a-10k-training/" target="_blank" rel="noreferrer">Read general race-training guidance <Icon name="open_in_new" size={16}/></a>
    </section>}
    <button className="run-activity-link" onClick={()=>nav('/train')}><span>Not training for a race?<strong>Log any activity instead</strong></span><Icon name="arrow_forward"/></button>
  </div>
}
