import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useApp } from '../store/AppContext'
import { TopBar } from '../components/TopBar'
import { Icon } from '../components/Icon'
import { addDays, daysBetween, shortDate, todayISO, weekday } from '../lib/date'
import { RACE_OPTIONS, scheduledRunKey, evaluateRunningPlan, minimumPlanWeeks, formatFinishTime, formatPace, formatPaceRange, generatePlan, parseRunTime, parseCurrentRun, planCapability, planPhase, planWeeks, raceLabel, suggestPlanStart, weekCapability } from '../lib/plan'
import type { PlanSession, RaceType, UserProfile } from '../types'
import './running.css'

const DAYS=['Mon','Tue','Wed','Thu','Fri','Sat','Sun']
export function Train() {
  const { profile, state, weightKg, updateProfile, toggleSession, addSession }=useApp()
  const nav=useNavigate()
  const [view,setView]=useState<'setup'|'schedule'|'overview'|'paces'>(profile.planStartDate?'schedule':'setup')
  const [buildStep,setBuildStep]=useState(0)
  const [draft,setDraft]=useState<UserProfile>({...profile,trainingDaysPerWeek:Math.max(3,Math.min(6,profile.trainingDaysPerWeek)),runPreferredDays:profile.runPreferredDays.length===Math.max(3,Math.min(6,profile.trainingDaysPerWeek))?profile.runPreferredDays:[1,3,5,0,4,6].slice(0,Math.max(3,Math.min(6,profile.trainingDaysPerWeek))),planStartDate:profile.planStartDate??suggestPlanStart()})
  const [goalText,setGoalText]=useState(profile.runGoalTimeMin?formatFinishTime(profile.runGoalTimeMin):'30:00')
  const [timed,setTimed]=useState(Boolean(profile.runGoalTimeMin))
  const [resultMode,setResultMode]=useState<'time'|'pace'|'none'>('time')
  const [resultText,setResultText]=useState(profile.runBenchmarkKnown?formatFinishTime(planCapability(profile).assessment.benchmarkPace*profile.runBenchmarkDistanceKm/60):'')
  const [error,setError]=useState('')
  const [saved,setSaved]=useState(false)
  const [checkTime,setCheckTime]=useState('')
  const [checkDistance,setCheckDistance]=useState<UserProfile['runBenchmarkDistanceKm']>(5)
  const [checkError,setCheckError]=useState('')
  const [weeklyKmText,setWeeklyKmText]=useState(profile.runWeeklyKm?.toString()??'')
  const [recentDaysText,setRecentDaysText]=useState(profile.runRecentDaysPerWeek?.toString()??'')
  const [weekIndex,setWeekIndex]=useState(Math.max(0,profile.planStartDate?Math.min(planWeeks(profile)-1,Math.floor(daysBetween(profile.planStartDate,todayISO())/7)):0))
  const goal=parseRunTime(goalText),enteredResult=parseCurrentRun(resultText),result=enteredResult?(resultMode==='pace'?enteredResult*draft.runBenchmarkDistanceKm:enteredResult):null
  const previewProfile=useMemo(()=>({...draft,sports:draft.sports.includes('running')?draft.sports:[...draft.sports,'running'] as UserProfile['sports'],runWeeklyKm:weeklyKmText===''?undefined:Number(weeklyKmText),runRecentDaysPerWeek:recentDaysText===''?undefined:Number(recentDaysText),runGoalTimeMin:timed?goal:null,runBenchmarkKnown:resultMode!=='none'&&Boolean(result),
    ...(resultMode!=='none'&&result?{runBenchmarkPaceSec:result*60/draft.runBenchmarkDistanceKm,...(draft.runBenchmarkDistanceKm===5?{bestFiveKmPaceSecPerKm:result*60/5}:draft.runBenchmarkDistanceKm===10?{bestTenKmPaceSecPerKm:result*60/10}:{})}:{})}),[draft,timed,goal,result,resultMode,weeklyKmText,recentDaysText])
  const preview=useMemo(()=>generatePlan(previewProfile,weightKg),[previewProfile,weightKg])
  const cap=planCapability(previewProfile),activeCap=planCapability(profile)
  const total=planWeeks(profile),activeStart=profile.planStartDate??suggestPlanStart()
  const weekStart=addDays(activeStart,weekIndex*7),weekEnd=addDays(weekStart,7)
  const regenerated=useMemo(()=>generatePlan(profile,weightKg),[profile,weightKg])
  const evaluation=evaluateRunningPlan(profile,regenerated)
  const sessions=regenerated.filter(s=>s.date>=weekStart&&s.date<weekEnd).map(s=>{
    const saved=state.sessions.find(r=>r.plan==='running'&&scheduledRunKey(r)===scheduledRunKey(s))
    return saved?{...s,id:saved.id,completed:saved.completed}:s
  })
  const previousRuns=state.sessions.filter(s=>s.plan==='running'&&s.completed&&s.date>=weekStart&&s.date<weekEnd&&!sessions.some(r=>scheduledRunKey(r)===scheduledRunKey(s)))
  function completeScheduledRun(session:PlanSession) {
    if(state.sessions.some(s=>s.id===session.id))toggleSession(session.id)
    else addSession({...session,completed:true})
  }
  const weeklyCap=weekCapability(profile,weekIndex)
  function setBaseline() {
    const minutes=parseRunTime(checkTime),pace=minutes?minutes*60/checkDistance:0
    if(!minutes||pace<120||pace>1800){setCheckError('Enter your actual 5K or 10K time, for example 35:00.');return}
    const next={...profile,runBenchmarkKnown:true,runBenchmarkDistanceKm:checkDistance,runBenchmarkPaceSec:pace,runCheckpoints:[],...(checkDistance===5?{bestFiveKmPaceSecPerKm:pace}:checkDistance===10?{bestTenKmPaceSecPerKm:pace}:{})}
    updateProfile(next,true);setDraft(next);setResultMode('time');setResultText(checkTime);setCheckTime('');setCheckError('');setSaved(true)
  }
  function recordCheckpoint() {
    const minutes=parseRunTime(checkTime),pace=minutes?minutes*60/checkDistance:0
    if(!minutes||pace<120||pace>1800){setCheckError('Enter a real result as mm:ss or h:mm:ss, between 2:00 and 30:00/km.');return}
    if(weekIndex>=total-1){setCheckError('This is the final week. Add your new result when building your next block.');return}
    updateProfile({...profile,runCheckpoints:[...(profile.runCheckpoints??[]).filter(c=>c.fromWeek!==weekIndex+1),{fromWeek:weekIndex+1,distanceKm:checkDistance,paceSec:pace}]},true)
    setCheckError('');setCheckTime('');setSaved(true)
  }
  const requiredPace=goal?goal*60/cap.raceKm:null
  const previewEvaluation=evaluateRunningPlan(previewProfile,preview)
  function navigateBuild(step:number) {
    if(step>buildStep) {
      if(buildStep===0&&(resultMode!=='none'&&(!result||result*60/draft.runBenchmarkDistanceKm<120||result*60/draft.runBenchmarkDistanceKm>1800))) {setError('Add a valid recent finish time or pace, or choose No result yet.');return}
      if(buildStep===0&&(weeklyKmText===''||recentDaysText===''||!Number.isFinite(+weeklyKmText)||+weeklyKmText<0||+weeklyKmText>200||!Number.isInteger(+recentDaysText)||+recentDaysText<0||+recentDaysText>7||!draft.runExperience||!Number.isFinite(draft.bestRunDistanceKm)||draft.bestRunDistanceKm<0||draft.bestRunDistanceKm>100)) {setError('Add your weekly distance, running days, longest run and experience. Enter 0 if you have not started running.');return}
      if(buildStep===1&&timed&&!goal) {setError('Enter your target finish time, for example 25:00 or 2:00:00.');return}
      if(buildStep===2&&(draft.runPreferredDays.length!==draft.trainingDaysPerWeek||!draft.planStartDate||draft.raceDate&&(daysBetween(draft.planStartDate,draft.raceDate)<6||daysBetween(draft.planStartDate,draft.raceDate)>181)||planWeeks(previewProfile)<minimumPlanWeeks(previewProfile))) {setError(`Select ${draft.trainingDaysPerWeek} running days and a ${minimumPlanWeeks(previewProfile)}–26 week block. For a distant event, start your race block closer to the event.`);return}
    }
    setError('');setBuildStep(step)
    document.querySelector('main')?.scrollTo({top:0,behavior:'auto'})
  }
  function changeRace(type:RaceType) {
    const race=RACE_OPTIONS.find(r=>r.id===type)!
    setDraft(p=>({...p,raceType:type,runPlanWeeks:race.weeks}))
    setGoalText(formatFinishTime(race.presets[type==='5k'||type==='10k'?2:1]));setSaved(false)
  }
  function save() {
    if(timed&&!goal){setError('Enter a finish time as mm:ss or h:mm:ss, for example 30:00 or 1:00:00.');return}
    if(resultMode!=='none'&&(!result||result*60/draft.runBenchmarkDistanceKm<120||result*60/draft.runBenchmarkDistanceKm>1800)){setError('Enter your current 5K/10K time or pace, or choose “No result yet”. Pace must be between 2:00 and 30:00/km.');return}
    if(weeklyKmText===''||recentDaysText===''||!Number.isFinite(Number(weeklyKmText))||Number(weeklyKmText)<0||Number(weeklyKmText)>200||!Number.isInteger(Number(recentDaysText))||Number(recentDaysText)<0||Number(recentDaysText)>7||!draft.runExperience){setError('Add your recent weekly km, running days and experience so the starting load fits you. Enter 0 km / 0 days if you are not running yet.');return}
    if(!Number.isFinite(draft.bestRunDistanceKm)||draft.bestRunDistanceKm<0||draft.bestRunDistanceKm>100){setError('Enter a longest comfortable run between 0 and 100 km.');return}
    if(draft.runPreferredDays.length!==draft.trainingDaysPerWeek){setError('Choose exactly your available number of training days.');return}
    if(!draft.planStartDate||draft.raceDate&&(daysBetween(draft.planStartDate,draft.raceDate)<6||daysBetween(draft.planStartDate,draft.raceDate)>181)){setError('Use a race block up to 26 weeks. For a distant event, move the start closer to the event.');return}
    if(planWeeks(previewProfile)<minimumPlanWeeks(previewProfile)){setError(`Use at least ${minimumPlanWeeks(previewProfile)} weeks for this profile, or change the event date. A short block cannot replace race preparation.`);return}
    updateProfile({...previewProfile,runCheckpoints:[],runWeekFeedback:[],sports:profile.sports.includes('running')?profile.sports:[...profile.sports,'running']},true)
    setError('');setSaved(true);setWeekIndex(0);setView('schedule')
  }
  const status=cap.assessment.difficulty
  return <div className={`run-page ${view==='schedule'?'is-week':''}`}><TopBar/><header className="page-heading"><h1>{view==='setup'?'Build your next chapter.':'Your running plan.'}</h1>{view!=='schedule'&&<p>{view==='setup'?'Your current level. Your goal. A week you can actually follow.':'Know the session. Find your pace. Show up.'}</p>}</header>
    <nav className="page-switch run-navigation" aria-label="Running sections">{([{id:'schedule',label:'This week'},{id:'overview',label:'Full plan'},{id:'paces',label:'Paces'},{id:'setup',label:'Build a plan'}] as const).map(t=><button key={t.id} aria-pressed={view===t.id} onClick={()=>{setView(t.id);setError('');if(t.id==='setup'){setBuildStep(0);setSaved(false)}}}>{t.label}</button>)}</nav>
    {view==='setup'&&<div className="run-setup">
      <ol className="run-build-steps" aria-label="Build plan progress">{['Runner','Goal','Week','Review'].map((label,index)=><li key={label}><button aria-current={index===buildStep?'step':undefined} disabled={index>buildStep} onClick={()=>navigateBuild(index)}><span>{index+1}</span>{label}</button></li>)}</ol>
      {buildStep===1&&<><section><h2>Pick your start line.</h2><p className="run-section-intro">From a first 5K to your next marathon.</p><div className="run-distances" role="group" aria-label="Race distance">{RACE_OPTIONS.map(r=><button key={r.id} aria-pressed={draft.raceType===r.id} onClick={()=>changeRace(r.id)}><strong>{r.label}</strong><small>{r.km} km</small></button>)}</div></section>
      <section><h2>What are you chasing?</h2><div className="run-goal-mode"><button aria-pressed={!timed} onClick={()=>setTimed(false)}>Finish comfortably</button><button aria-pressed={timed} onClick={()=>setTimed(true)}>A finish time</button></div>
      {timed&&<><div className="run-time-presets">{RACE_OPTIONS.find(r=>r.id===draft.raceType)!.presets.map(min=><button key={min} aria-pressed={goal===min} onClick={()=>setGoalText(formatFinishTime(min))}>Sub {formatFinishTime(min)}</button>)}</div><label className="run-field">Custom finish time<input value={goalText} onChange={e=>setGoalText(e.target.value)} inputMode="text" placeholder="mm:ss or h:mm:ss" aria-describedby="run-time-help"/></label><p id="run-time-help" className="run-help">Any target: 28:30 means sub-28:30; 1:00:00 means sub-60 minutes.</p></>}
      <div className="run-goal-preview"><Icon name="flag" size={24}/><div><strong>{timed&&goal?`${raceLabel(draft.raceType)} · Sub ${formatFinishTime(goal)}`:'A confident finish'}</strong><span>{timed&&requiredPace?`${formatPace(requiredPace)} average race pace required`:'No time pressure. Build consistency and endurance.'}</span></div></div><p className="run-help">{status==='unrealistic'?'This is a longer-term ambition. This block starts at your current ability; reaching the target may take several blocks.':status==='unknown'?'No timed baseline yet: your first block will use conversational effort.':'Session paces start from your recent result, not your goal pace.'}</p></section></>}
      {buildStep===0&&<section><h2>Start with the real you.</h2><p className="run-section-intro">What can you run now? Not your goal—your recent ability.</p><div className="run-goal-mode" role="group" aria-label="Current ability input">{([{id:'time',label:'Finish time'},{id:'pace',label:'Pace per km'},{id:'none',label:'No result yet'}] as const).map(mode=><button key={mode.id} aria-pressed={resultMode===mode.id} onClick={()=>{if(mode.id!==resultMode&&mode.id!=='none'){setResultText(result?formatFinishTime(mode.id==='pace'?result/draft.runBenchmarkDistanceKm:result):'')}setResultMode(mode.id)}}>{mode.label}</button>)}</div>
      {resultMode!=='none'&&<><div className="run-fields"><label className="run-field">Result distance<select value={draft.runBenchmarkDistanceKm} onChange={e=>{setDraft(p=>({...p,runBenchmarkDistanceKm:+e.target.value as UserProfile['runBenchmarkDistanceKm']}));setResultText('')}}><option value={5}>5 km</option><option value={10}>10 km</option><option value={21.1}>Half marathon · 21.1 km</option><option value={42.2}>Marathon · 42.2 km</option></select></label><label className="run-field">{resultMode==='pace'?'Current pace · min/km':'Recent finish time'}<input value={resultText} onChange={e=>setResultText(e.target.value)} placeholder={resultMode==='pace'?'e.g. 7:00':'mm:ss or h:mm:ss'}/></label></div><p className="run-help">Use a recent race or hard, sustainable effort—not a relaxed jog or your target time. Estimates are OK; initial ranges are provisional.</p>{previewProfile.runBenchmarkKnown&&<div className="run-input-preview"><strong>{draft.runBenchmarkDistanceKm} km in {formatFinishTime(result!)} · {formatPace(result!*60/draft.runBenchmarkDistanceKm)}</strong><dl><div><dt>Week 1 easy pace</dt><dd>{formatPaceRange(cap.easyPace)}</dd></div><div><dt>Starting tempo guide</dt><dd>{formatPaceRange(cap.tempoPace,15)}</dd></div><div><dt>Starting interval guide</dt><dd>{formatPaceRange(cap.intervalPace,10)}</dd></div></dl></div>}</>}
      <label className="run-field">Longest comfortable run · km<input type="number" min="0" max="100" step=".1" value={draft.bestRunDistanceKm} onChange={e=>setDraft(p=>({...p,bestRunDistanceKm:Number(e.target.value)}))}/></label>
      <div className="run-fields"><label className="run-field">Recent weekly distance · km<input type="number" min="0" max="200" step=".5" value={weeklyKmText} onChange={e=>setWeeklyKmText(e.target.value)} placeholder="e.g. 15"/></label><label className="run-field">Recent running days / week<input type="number" min="0" max="7" step="1" value={recentDaysText} onChange={e=>setRecentDaysText(e.target.value)} placeholder="e.g. 3"/></label></div><p className="run-help">Use your average over the last 3–4 weeks. Not running yet? Enter 0; start with short, easy run/walk sessions.</p><label className="run-field">Running experience<select value={draft.runExperience??''} onChange={e=>setDraft(p=>({...p,runExperience:e.target.value as UserProfile['runExperience']}))}><option value="" disabled>Choose your current level</option><option value="new">New runner</option><option value="returning">Returning after a break</option><option value="regular">Running consistently</option></select></label><label className="run-checkbox"><input type="checkbox" checked={Boolean(draft.runBaseOnly)} onChange={e=>setDraft(p=>({...p,runBaseOnly:e.target.checked}))}/> Easy base only · skip demanding speed sessions</label><p className="run-help">Pain, injury or illness? Get appropriate advice before training. The app cannot assess medical readiness.</p>
      </section>}
      {buildStep===2&&<section><h2>Make room for your runs.</h2><p className="run-section-intro">Choose days you can keep. Rest is part of the plan.</p><div className="run-fields"><label className="run-field">Run days per week<select value={Math.min(6,draft.trainingDaysPerWeek)} onChange={e=>{const n=+e.target.value;setDraft(p=>({...p,trainingDaysPerWeek:n,runPreferredDays:[1,3,5,0,4,6].slice(0,n)}))}}>{[3,4,5,6].map(n=><option key={n} value={n}>{n} days</option>)}</select></label><label className="run-field">Training block<select value={draft.runPlanWeeks} onChange={e=>setDraft(p=>({...p,runPlanWeeks:+e.target.value}))}>{[4,6,8,10,12,14,16,18,20,24,26].map(n=><option key={n} value={n}>{n} weeks</option>)}</select></label></div>
      <div className="run-day-picker" role="group" aria-label="Preferred running days">{DAYS.map((d,i)=><button key={d} aria-pressed={draft.runPreferredDays.includes(i)} onClick={()=>setDraft(p=>({...p,runPreferredDays:p.runPreferredDays.includes(i)?p.runPreferredDays.filter(v=>v!==i):p.runPreferredDays.length<p.trainingDaysPerWeek?[...p.runPreferredDays,i]:p.runPreferredDays}))}>{d}</button>)}</div>
      <div className="run-fields"><label className="run-field">Start date<input type="date" value={draft.planStartDate??''} onChange={e=>setDraft(p=>({...p,planStartDate:e.target.value}))}/></label><label className="run-field">Event date · optional<input type="date" value={draft.raceDate??''} onChange={e=>setDraft(p=>({...p,raceDate:e.target.value||null}))}/></label></div><p className="run-help">Recommended minimum for your profile: {minimumPlanWeeks(previewProfile)} weeks. An event date overrides block length.</p>{draft.raceDate&&daysBetween(draft.planStartDate!,draft.raceDate)>181&&<div className="run-assessment"><h3>Your event is further away.</h3><p>Build your base now, then begin a focused race block closer to the event. Do not repeat peak training for months.</p><button className="run-inline-action" onClick={()=>setDraft(p=>({...p,planStartDate:addDays(p.raceDate!,-Math.max(minimumPlanWeeks(previewProfile),p.runPlanWeeks)*7+1)}))}>Use a {Math.max(minimumPlanWeeks(previewProfile),draft.runPlanWeeks)}-week start date</button></div>}</section>}
      {buildStep===3&&<section className="run-plan-preview"><h2>Your plan, before you commit.</h2><div className="run-review-facts"><div><span>Goal</span><strong>{raceLabel(draft.raceType)} · {timed&&goal?`Sub ${formatFinishTime(goal)}`:'Finish comfortably'}</strong><button onClick={()=>navigateBuild(1)}>Edit goal</button></div><div><span>Schedule</span><strong>{planWeeks(previewProfile)} weeks · {draft.trainingDaysPerWeek} days/week</strong><small>{draft.runPreferredDays.slice().sort((a,b)=>a-b).map(d=>DAYS[d]).join(' · ')}</small><button onClick={()=>navigateBuild(2)}>Edit week</button></div><div><span>Starting point</span><strong>{weeklyKmText} km/week · longest {draft.bestRunDistanceKm} km</strong><button onClick={()=>navigateBuild(0)}>Edit runner</button></div><div><span>Peak long run</span><strong>{previewEvaluation.peakKm.toFixed(1)} km · week {previewEvaluation.peakWeek??'—'}</strong></div></div><div className="run-assessment"><h3>{previewEvaluation.needsBase?'Build your base first':'A race-focused training block'}</h3><p>{previewEvaluation.reason??'Easy runs, quality work, long runs and a lighter finish. Pace targets progress from your current ability.'}</p><p>Planned progression is a target, not a guarantee. Report difficult weeks to ease the next sessions.</p></div><h3 className="run-preview-heading">A look at week 1</h3><div className="run-preview-sessions">{preview.filter(s=>s.date>=draft.planStartDate!&&s.date<addDays(draft.planStartDate!,7)).map(s=><div key={s.id}><span>{weekday(s.date)}</span><div><strong>{s.title}</strong><small>{s.runBrief?.pace}</small></div><b>{s.distanceKm} km</b></div>)}</div><p className="run-help">Saving replaces upcoming prescriptions. Completed runs and manual activity logs are kept.</p></section>}
      {error&&<p className="run-error" role="alert">{error}</p>}<div className="run-builder-actions">{buildStep>0&&<button className="run-back" onClick={()=>navigateBuild(buildStep-1)}><Icon name="arrow_back" size={18}/>Back</button>}{buildStep<3?<button className="run-save" onClick={()=>navigateBuild(buildStep+1)}>Continue to {['','goal','your week','review'][buildStep+1]}<Icon name="arrow_forward" size={20}/></button>:<button type="button" className="run-save" onClick={save}>{profile.planStartDate?'Update running plan':'Save my running plan'}<Icon name="arrow_forward" size={20}/></button>}</div>
    </div>}
    {view==='schedule'&&<section className="run-schedule">{!profile.planStartDate?<div className="run-empty"><h2>Your next start line.</h2><p>Choose your distance, time and available days to build a schedule.</p><button onClick={()=>setView('setup')}>Build my plan</button></div>:<>
      <div className="run-schedule-title"><h2>{raceLabel(profile.raceType)} · {evaluation.missingLoad?'Complete runner profile':evaluation.needsBase?'Base-building block':activeCap.selectedGoalLabel}</h2>{(profile.runGoalTimeMin||profile.raceDate)&&<p>{profile.runGoalTimeMin?`Race target: ${formatPace(profile.runGoalTimeMin*60/activeCap.raceKm)}`:''}{profile.raceDate?` · Event ${shortDate(profile.raceDate)}`:''}</p>}</div>
      <div className="run-week-nav"><button aria-label="Previous training week" disabled={weekIndex===0} onClick={()=>setWeekIndex(i=>i-1)}><Icon name="chevron_left"/></button><div><strong>Week {weekIndex+1} / {total}</strong><span>{shortDate(weekStart)} – {shortDate(addDays(weekStart,6))}</span></div><button aria-label="Next training week" disabled={weekIndex>=total-1} onClick={()=>setWeekIndex(i=>i+1)}><Icon name="chevron_right"/></button></div>
      <p className="run-phase">{evaluation.needsBase?'Base-building':weekIndex>=total-(profile.raceType==='marathon'?3:profile.raceType==='half-marathon'?2:1)?'Taper & recover':(weekIndex+1)%4===0?'Recovery & progress check':planPhase(weekIndex+1,total)}</p>
      <div className="run-week-totals"><div><strong>{sessions.reduce((sum,s)=>sum+(s.distanceKm??0),0).toFixed(1)}<small> km</small></strong><span>This week</span></div><div><strong>{Math.max(0,...sessions.filter(s=>s.runKind==='long').map(s=>s.distanceKm??0))}<small> km</small></strong><span>Longest run</span></div><div><strong>{sessions.filter(s=>s.completed).length}<small> / {sessions.length}</small></strong><span>Completed</span></div></div>
      {evaluation.needsBase&&<p className="run-base-notice"><Icon name="info" size={18}/><span>This block builds your base—not full race preparation. <button onClick={()=>setView('overview')}>See plan review</button></span></p>}
      {total>26&&<p className="run-base-notice"><Icon name="info" size={18}/><span>This older plan spans {total} weeks. Rebuild a focused block closer to your event. <button onClick={()=>{setView('setup');setBuildStep(2)}}>Review dates</button></span></p>}
      {!weeklyCap.known&&<section className="run-checkpoint run-baseline"><h3>Set your training paces</h3><p>No recent timed result saved. Enter your actual result to calculate easy, tempo and interval paces—not your goal time.</p><div className="run-fields"><label className="run-field">Current result distance<select value={checkDistance} onChange={e=>setCheckDistance(+e.target.value as 5|10)}><option value={5}>5 km</option><option value={10}>10 km</option></select></label><label className="run-field">Current finish time<input value={checkTime} onChange={e=>setCheckTime(e.target.value)} placeholder="e.g. 35:00"/></label></div>{checkError&&<p className="run-error" role="alert">{checkError}</p>}<button className="run-save" onClick={setBaseline}>Calculate my training paces<Icon name="arrow_forward" size={18}/></button><p>No timed result? Keep runs conversational until you have one.</p></section>}
      <h3 className="run-daily-heading">Your daily plan · week {weekIndex+1}</h3>
      {Array.from({length:7},(_,i)=>addDays(weekStart,i)).map(date=>{const runs=sessions.filter(s=>s.date===date);return <div className="run-agenda-day" key={date}><div className="run-agenda-date"><strong>{weekday(date)}</strong><span>{shortDate(date)}</span></div><div>{runs.length?runs.map(s=><article className={`run-workout ${s.completed?'is-done':''}`} key={s.id}><div><h3>{s.title}</h3>{s.runBrief?<><strong className="run-session-pace">{s.runBrief.pace}</strong><dl className="run-session-steps">{s.runBrief.steps.map(step=><div key={step.label}><dt>{step.label}</dt><dd>{step.value}</dd></div>)}</dl><p>{s.runBrief.note}</p></>:<p>{s.detail}</p>}<small>{s.durationMin} min · ≈ {s.distanceKm} km · {s.kcal} kcal estimate</small></div><button type="button" aria-pressed={s.completed} aria-label={`${s.completed?'Mark incomplete':'Complete'}: ${s.title} on ${date}`} onClick={()=>completeScheduledRun(s)}><Icon name={s.completed?'check_circle':'radio_button_unchecked'} size={24}/></button></article>):<p className="run-rest">{date>addDays(activeStart,total*7-1)?'Outside this block': 'Rest / gentle mobility. No run scheduled.'}</p>}</div></div>})}
      {previousRuns.length>0&&<details className="run-previous-history"><summary>Previous completed runs · {previousRuns.length}</summary><p>These were completed under an earlier plan. They remain in your activity history, but do not replace today’s prescription.</p>{previousRuns.map(s=><div key={s.id}><strong>{weekday(s.date)} · {shortDate(s.date)}</strong><span>{s.title} · {s.distanceKm??'—'} km · {s.durationMin} min</span></div>)}</details>}
      <section className="run-week-response"><h3>How did week {weekIndex+1} feel?</h3><div className="run-goal-mode">{([{id:'comfortable',label:'Manageable'},{id:'hard',label:'Too hard'},{id:'missed',label:'Missed most sessions'}] as const).map(item=><button key={item.id} aria-pressed={profile.runWeekFeedback?.find(f=>f.week===weekIndex)?.response===item.id} onClick={()=>{updateProfile({...profile,runWeekFeedback:[...(profile.runWeekFeedback??[]).filter(f=>f.week!==weekIndex),{week:weekIndex,response:item.id}]},true);setSaved(true)}}>{item.label}</button>)}</div><p>Too hard or missed most sessions? Upcoming load eases and pace progression pauses. Completed runs stay unchanged.</p></section>
      <section className="run-checkpoint"><h3>Ran a new personal benchmark?</h3><p>Use a recent timed result, not an easy jog. Recalculates from week {weekIndex+2}; completed runs stay unchanged.</p><div className="run-fields"><label className="run-field">Benchmark distance<select value={checkDistance} onChange={e=>setCheckDistance(+e.target.value as 5|10)}><option value={5}>5 km</option><option value={10}>10 km</option></select></label><label className="run-field">New finish time<input value={checkTime} onChange={e=>setCheckTime(e.target.value)} placeholder="e.g. 32:00"/></label></div>{checkError&&<p role="alert" className="run-error">{checkError}</p>}<button className="run-save" onClick={recordCheckpoint}>Recalculate upcoming weeks <Icon name="arrow_forward" size={18}/></button></section>
    </>}</section>}
    {view==='overview'&&<section className="run-overview">{profile.planStartDate?<><h2>{raceLabel(profile.raceType)} · {activeCap.selectedGoalLabel}</h2><p className="run-section-intro">{total} weeks · {profile.trainingDaysPerWeek} running days per week · starts {shortDate(activeStart)}</p><section className="run-plan-readiness"><h3>{evaluation.status}</h3><dl><div><dt>Peak long run</dt><dd>{evaluation.peakKm.toFixed(1)} km · week {evaluation.peakWeek??'—'}</dd></div><div><dt>Your starting load</dt><dd>{profile.runWeeklyKm??'Not set'} km/week</dd></div><div><dt>Current result</dt><dd>{profile.runBenchmarkKnown?`${activeCap.assessment.benchmarkKm} km · ${formatFinishTime(activeCap.assessment.benchmarkKm*activeCap.assessment.benchmarkPace/60)}`:'No timed result'}</dd></div></dl>{evaluation.reason&&<p>{evaluation.reason}</p>}<p>Paces are conditional training targets—not measured fitness or a guaranteed finish time.</p></section><RunProgression profile={profile} sessions={regenerated} selectedWeek={weekIndex} onSelect={week=>{setWeekIndex(week);setView('schedule');document.querySelector('main')?.scrollTo({top:0})}}/><button className="run-save" onClick={()=>{setBuildStep(0);setView('setup')}}>Review runner & rebuild plan<Icon name="arrow_forward" size={20}/></button></>:<div className="run-empty"><h2>A plan starts with you.</h2><p>Add your running level and available days first.</p><button onClick={()=>setView('setup')}>Build my plan</button></div>}</section>}
    {view==='paces'&&<section className="run-paces"><h2>Train at the right effort</h2><p>Week {weekIndex+1} ranges · min/km. Heat, hills and recovery matter more than hitting an exact number. The schedule decides which types to run.</p>{!weeklyCap.known?<p className="run-assessment">No current ability entered yet. Use conversational run/walk effort until you add a 5K/10K time or pace.</p>:<div className="run-pace-list">{[{label:'Easy & long',pace:weeklyCap.easyPace,spread:30,why:'Full sentences. Most running belongs here.'},{label:'Tempo',pace:weeklyCap.tempoPace,spread:15,why:'Controlled hard effort. Short phrases.'},{label:'Intervals',pace:weeklyCap.intervalPace,spread:10,why:'Short repeats with recovery. Never sprint.'}].map(item=><div key={item.label}><div><h3>{item.label}</h3><p>{item.why}</p></div><strong>{formatPaceRange(item.pace,item.spread)}</strong></div>)}</div>}
      <details><summary>How the estimate works</summary><ul><li>Race estimates: result time × (race distance / result distance)^1.06. Endurance readiness matters, especially for marathons.</li><li>Planned pace progression starts from your current result, runner level and goal. It is a conditional target, not predicted fitness.</li><li>Easy pace progresses more gently than quality pace; recovery weeks ease off. Too-hard or missed-week feedback pauses progression.</li><li>Long runs and total mileage are checked together. A block too small for race preparation is labelled base-building.</li><li>Numerical ranges, mileage caps and endurance checkpoints are FitCore heuristics—not Garmin/Runna algorithms or a medical assessment.</li><li>If sessions feel too hard, repeat a week or slow down. No plan guarantees a sub-time.</li></ul></details><a href="https://support.runna.com/en/articles/6205998-adjusting-your-estimated-race-time-and-pace-targets" target="_blank" rel="noreferrer">How current ability informs training paces <Icon name="open_in_new" size={16}/></a><a href="https://www.baa.org/races/boston-marathon/info-for-athletes/boston-marathon-training/" target="_blank" rel="noreferrer">Marathon training structure <Icon name="open_in_new" size={16}/></a>
    </section>}
    {saved&&<p className="run-feedback" role="status"><Icon name="check_circle" size={16}/>Saved on this device. History kept.</p>}
    <button className="run-activity-link" onClick={()=>nav('/train')}><span>Not training for a race?<strong>Log any activity instead</strong></span><Icon name="arrow_forward"/></button>
  </div>
}

function RunProgression({profile,sessions,selectedWeek,onSelect}:{profile:UserProfile;sessions:PlanSession[];selectedWeek:number;onSelect:(week:number)=>void}) {
  const start=profile.planStartDate!,weeks=planWeeks(profile)
  const evaluation=evaluateRunningPlan(profile,sessions)
  return <section className="run-progression"><h3>{evaluation.needsBase?'Base-building schedule · not race preparation':'Your week-by-week race build'}</h3><p>All paces are min/km. Quality ranges are conditional training targets, not predicted fitness. Tap a week to see its sessions.</p><div className="run-progression-scroll" tabIndex={0} role="region" aria-label="Weekly distance and pace progression"><table><thead><tr><th scope="col">Week</th><th scope="col">Easy range</th><th scope="col">Quality session</th><th scope="col">{evaluation.needsBase?'Longest base / total':'Long run / total'}</th></tr></thead><tbody>{Array.from({length:weeks},(_,week)=>{
    const begin=addDays(start,week*7),end=addDays(begin,7),runs=sessions.filter(s=>s.date>=begin&&s.date<end)
    const cap=weekCapability(profile,week),quality=runs.find(s=>['Tempo','Intervals','Benchmark'].includes(s.zone??'')),long=runs.find(s=>s.runKind==='long'||s.title==='Easy endurance run')
    return <tr key={week} className={week===selectedWeek?'is-current':''}><th scope="row"><button aria-pressed={week===selectedWeek} onClick={()=>onSelect(week)}>Week {week+1}</button></th><td>{cap.known?formatPaceRange(cap.easyPace):'Talk pace'}</td><td>{quality?<><strong>{quality.title}</strong><span>{quality.runBrief?.pace}</span><small>{quality.runBrief?.steps.find(s=>s.label==='Main set')?.value}</small></>:<><strong>Easy Run</strong><span>{!evaluation.needsBase&&week>=weeks-(profile.raceType==='marathon'?3:profile.raceType==='half-marathon'?2:1)?'Taper':week<2?'Optional strides':'Build your base'}</span></>}</td><td><strong>{long?.distanceKm??'—'} km {evaluation.needsBase?'base':'long'}</strong><span>≈ {runs.reduce((sum,s)=>sum+(s.distanceKm??0),0).toFixed(1)} km total</span></td></tr>
  })}</tbody></table></div></section>
}
