export interface SetDraft { reps: string; weightKg: string; holdSeconds: string }
export function StrengthSets({ sets, onChange, mode, weighted, implementCount, onImplementCountChange, sides = 1 }: { sets: SetDraft[]; onChange: (sets: SetDraft[]) => void; mode: 'reps' | 'hold'; weighted: boolean; implementCount: 1 | 2; onImplementCountChange: (count: 1 | 2) => void; sides?: 1 | 2 }) {
  function update(index: number, patch: Partial<SetDraft>) { onChange(sets.map((set, i) => i === index ? { ...set, ...patch } : set)) }
  const volume = sets.reduce((total, set) => total + (+set.reps || 0) * (+set.weightKg || 0) * implementCount * sides, 0)
  return <fieldset className="strength-sets"><legend>Log your sets</legend>
    {weighted && <><label className="home-form-label">Weights used<select value={implementCount} onChange={event => onImplementCountChange(+event.target.value as 1 | 2)}><option value={1}>One weight</option><option value={2}>Two equal weights</option></select></label><p className="home-form-note">Enter kg for ONE dumbbell or kettlebell. For a barbell, choose one weight and enter the total including the bar. For unilateral work, enter reps per side.</p></>}
    <div className={`strength-set-head ${weighted ? 'has-weight' : ''}`}><span>Set</span><span>{mode === 'hold' ? 'Seconds' : 'Reps'}</span>{weighted && <span>kg / weight</span>}<span /></div>
    {sets.map((set, index) => <div className={`strength-set-row ${weighted ? 'has-weight' : ''}`} key={index}><strong>{index + 1}</strong><input required type="number" inputMode="numeric" min={1} max={mode === 'hold' ? 3600 : 1000} step={1} value={mode === 'hold' ? set.holdSeconds : set.reps} aria-label={`Set ${index + 1} ${mode === 'hold' ? 'seconds' : 'reps'}`} onChange={event => update(index, mode === 'hold' ? { holdSeconds: event.target.value } : { reps: event.target.value })} />{weighted && <input required type="number" inputMode="decimal" min={0} max={1000} step="any" value={set.weightKg} placeholder="kg" aria-label={`Set ${index + 1} weight in kg`} onChange={event => update(index, { weightKg: event.target.value })} />}<button type="button" disabled={sets.length === 1} aria-label={`Remove set ${index + 1}`} onClick={() => onChange(sets.filter((_, i) => i !== index))}>Remove</button></div>)}
    <button className="strength-add-set" type="button" disabled={sets.length >= 30} onClick={() => onChange([...sets, { ...sets[sets.length - 1] }])}>Add set</button>
    <p className="strength-volume">{sets.length} {sets.length === 1 ? 'set' : 'sets'} · {mode === 'hold' ? `${sets.reduce((total, set) => total + (+set.holdSeconds || 0), 0)} seconds held` : `${sets.reduce((total, set) => total + (+set.reps || 0), 0)} reps${weighted ? ` · ${volume.toLocaleString()} kg lifting volume` : ' · bodyweight'}`}</p>
  </fieldset>
}
