import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import ts from 'typescript';
const compile = file => ts.transpileModule(readFileSync(new URL(file, import.meta.url), 'utf8'), { compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 } }).outputText;
const url = js => `data:text/javascript;base64,${Buffer.from(js).toString('base64')}`;
const dateUrl = url(compile('../src/lib/date.ts'));
const { showUpStreak } = await import(url(compile('../src/lib/streak.ts').replace("'./date'", JSON.stringify(dateUrl))));
const today = '2026-10-07';
const state = dates => ({ foods: dates.map(date => ({ date })), sessions: [], weights: [] });
assert.equal(showUpStreak(state([]), today).current, 0);
const mixed = { foods: [{ date: today }, { date: today }], weights: [{ date: today, weightKg: 70 }], sessions: [{ date: today, completed: true, type: 'strength' }] };
assert.equal(showUpStreak(mixed, today).current, 1);
assert.equal(showUpStreak(mixed, today).total, 1);
assert.equal(showUpStreak({ ...state([]), weights: [{ date: today, weightKg: 70, source: 'onboarding' }], sessions: [{ date: today, completed: false, type: 'run' }, { date: today, completed: true, type: 'rest' }] }, today).current, 0);
assert.equal(showUpStreak(state(['2026-10-05', '2026-10-06']), today).current, 2);
assert.equal(showUpStreak(state(['2026-10-03', '2026-10-04']), today).current, 0);
const rescue = showUpStreak(state(['2026-10-03', '2026-10-04', '2026-10-05', today]), today);
assert.equal(rescue.current, 4);
assert.ok(rescue.rescued.has('2026-10-06'));
assert.equal(rescue.rescueAvailable, false);
assert.equal(showUpStreak(state(['2026-10-05']), today).pendingRescue, true);
const twice = showUpStreak(state(['2026-10-05', '2026-10-07', '2026-10-09']), '2026-10-09');
assert.equal(twice.current, 1);
assert.equal(twice.best, 2);
const newWeek = showUpStreak(state(['2026-09-28', '2026-09-30', '2026-10-01', '2026-10-02', '2026-10-03', '2026-10-04', '2026-10-05', '2026-10-07']), today);
assert.equal(newWeek.current, 8);
assert.equal(newWeek.rescued.size, 2);
assert.equal(newWeek.earned.length, 2);
assert.equal(showUpStreak(state(['2026-10-06', '2026-10-08', '2026-02-30', 'garbage']), today).total, 1);
assert.equal(showUpStreak(state(['2026-10-05', today]), today).current, 2);
assert.equal(showUpStreak(state([today]), today).current, 1);
assert.equal(showUpStreak(state(['2025-12-31', '2026-01-01']), '2026-01-01').current, 2);
console.log('PASS: deduplication, baseline/rest/planned exclusions, pending today, reset, weekly rescue, second gap, weekly renewal, milestones, invalid/future dates, deletion, year boundary.');
