// FitCore domain types — single source of truth for app data shapes.

export type Sex = 'male' | 'female'
export type Goal = 'lose' | 'maintain' | 'gain'
export type Sport = 'running' | 'strength' | 'badminton' | 'pickleball'
export type ActivityLevel = 'sedentary' | 'light' | 'moderate' | 'high' | 'athlete'
export type HalfMarathonGoal = 'finish' | 'sub245' | 'sub240' | 'sub235' | 'sub230' | 'sub215' | 'sub200' | 'sub145'
/** Goal race distance for the running plan. */
export type RaceType = 'half-marathon' | 'marathon'

/** Eating protocol / diet mode layered on top of calorie tracking. */
export type DietMode = 'standard' | 'omad' | '16:8' | 'keto' | 'egg'

export interface NotifPrefs {
  morningBrief: boolean
  underFuelAlert: boolean
  preRace: boolean
}

export interface Wearables {
  appleHealth: boolean
  garmin: boolean
  strava: boolean
}

export interface UserProfile {
  name: string
  sex: Sex
  age: number
  heightCm: number
  startWeightKg: number
  goal: Goal
  sports: Sport[]
  /** ISO yyyy-mm-dd of the goal race, or null if none. */
  raceDate: string | null
  /** ISO yyyy-mm-dd of the first Monday of the training plan, or null if not started. */
  planStartDate: string | null
  /** Goal race distance: half or full marathon. */
  raceType: RaceType
  /** How many days per week the runner wants to train (3-7). */
  trainingDaysPerWeek: number
  /** Half-marathon finish concept used to derive target race pace. */
  halfMarathonGoal: HalfMarathonGoal
  /** Legacy target half-marathon finish in minutes, migrated when present. */
  targetFinishMin?: number | null
  /** Longest recent comfortable run used to scale the running plan. */
  bestRunDistanceKm: number
  /** Current best sustainable pace for that run, in seconds per km. */
  bestRunPaceSecPerKm: number
  /** Current best 5K pace in seconds per km. */
  bestFiveKmPaceSecPerKm: number
  /** Current best 10K pace in seconds per km. */
  bestTenKmPaceSecPerKm: number
  /** Preferred run weekdays, Monday=0 ... Sunday=6. */
  runPreferredDays: number[]
  activity: ActivityLevel
  /** Daily calorie target. If null, computed from TDEE + goal. */
  calorieTargetOverride: number | null
  /** Protein target in g per kg bodyweight. */
  proteinPerKg: number
  /** Active eating protocol. Shapes macro split, fasting window, and warnings. */
  dietMode: DietMode
  /** Net-carb ceiling for keto (grams/day). */
  netCarbCapG: number
  /** Hour (0-23) the eating window opens for OMAD / 16:8. */
  eatingWindowStartHour: number
  units: 'metric' | 'imperial'
  wearables: Wearables
  notif: NotifPrefs
  /** Optional Anthropic API key — enables real Claude vision food detection + live coach. */
  anthropicApiKey: string
  onboarded: boolean
}

export type MealSlot = 'breakfast' | 'lunch' | 'dinner' | 'snack'

export interface FoodEntry {
  id: string
  name: string
  emoji: string
  /** ISO yyyy-mm-dd */
  date: string
  /** ISO timestamp of when logged */
  loggedAt: string
  slot: MealSlot
  kcal: number
  protein: number
  carbs: number
  fat: number
  servings: number
  /** 0..1 AI detection confidence; 1 for manual entries */
  confidence: number
  /** base64 data URL thumbnail if captured via photo */
  photo?: string
}

export interface WeightEntry {
  id: string
  /** ISO yyyy-mm-dd */
  date: string
  weightKg: number
  neckCm?: number
  waistCm?: number
  hipCm?: number
}

export interface ProgressPhoto {
  id: string
  date: string
  /** on-device base64 data URL */
  dataUrl: string
}

export type SessionType = 'run' | 'strength' | 'sport' | 'rest'

export interface PlanSession {
  id: string
  /** ISO yyyy-mm-dd */
  date: string
  type: SessionType
  title: string
  /** short technical descriptor, e.g. "45 min • Z2 HR" */
  detail: string
  durationMin: number
  /** estimated distance for runs (km) */
  distanceKm?: number
  zone?: string
  /** estimated calorie burn */
  kcal: number
  completed: boolean
  /** identifies which plan generated it */
  plan: 'running' | 'strength' | 'sport' | 'manual'
  icon: string
  /** True when logged by the user instead of generated by the plan. */
  manual?: boolean
}

export interface AppState {
  profile: UserProfile
  foods: FoodEntry[]
  weights: WeightEntry[]
  photos: ProgressPhoto[]
  sessions: PlanSession[]
  /** version for migrations */
  v: number
}

export interface MacroTargets {
  kcal: number
  protein: number
  carbs: number
  fat: number
}

export interface DayFuel {
  date: string
  baseTarget: number
  trainingBonus: number
  budget: number
  consumed: number
  remaining: number
  protein: number
  carbs: number
  fat: number
  proteinTarget: number
  carbTarget: number
  fatTarget: number
}
